### ISSUE TITLE
index_for uses isize, and may panic

### ISSUE THREAD

**Issue by marshallpierce** [jonhoo/hdrsample#11]
It seems like we should be able to guarantee that those indexes are positive, which should hopefully also make us confident that it won't panic.

**Comment by jonhoo** [comment]
This is fixed by #12, right?

**Comment by marshallpierce** [comment]
Probably. I want to walk through that logic one more time before I call it good.

**Comment by marshallpierce** [comment]
With the tighter guarantees about unit magnitude + sub bucket count magnitude, I'm now comfortable with index_for.

I don't see why it would panic with out-of-range values. Small values will get mapped to bucket 0 and sub bucket 0. Large values (beyond what should be supported) will still get mapped to an index; the index just won't be one that exists in the counts vec.
